<a href="https://colab.research.google.com/github/CHIRANJEEVBHATT/Python/blob/main/Exp1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importing libraries

In [1]:
import numpy as np

# Creating array using inbuilt functions

In [2]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [3]:
a1= np.arange(0,10)

In [4]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(type(a1))

<class 'numpy.ndarray'>


In [6]:
print(a1.ndim)

1


In [7]:
print(a1.shape)

(10,)


In [8]:
print(a1.size)

10


In [9]:
a2= np.arange(0,10,2)

In [10]:
print(a2)

[0 2 4 6 8]


# Creating array filled with zeroes

In [11]:
a3= np.zeros(10)

In [12]:
print(a3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
a4= np.zeros((10,5))

In [14]:
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
a5= np.full((10,5),4)
print(a5)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


# Creating array filled with random number

In [16]:
a6= np.random.random((4,2))

In [17]:
print(a6)

[[0.27414495 0.18333318]
 [0.27787636 0.84952875]
 [0.8330455  0.64260295]
 [0.65266243 0.52111015]]


In [18]:
a7= np.random.randn(4,2)

In [19]:
a7.mean()

np.float64(0.32711325419921855)

In [20]:
a7.std()

np.float64(0.8581238361219151)

In [21]:
print(a7)

[[ 0.14028251  1.49147691]
 [ 0.06487334  1.33599928]
 [-0.9230851   1.23894341]
 [-0.19392455 -0.53765976]]


In [22]:
a8= np.identity(4)

In [23]:
print(a8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Creating nd array using list

In [24]:
l1= [1,2,3,4]
l1

[1, 2, 3, 4]

In [25]:
type(l1)

list

In [26]:
l2= np.array(l1)
l2

array([1, 2, 3, 4])

In [27]:
type(l2)

numpy.ndarray

In [28]:
l3= np.array([[1,2,3], [4,5,6], [7,8,9]])
l3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array indexing

In [29]:
l2

array([1, 2, 3, 4])

In [30]:
l2[2]

np.int64(3)

In [31]:
print(l2[2])

3


In [32]:
print(l2[-2])

3


In [33]:
l3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(l3[1,1])

5


# Boolean indexing

In [35]:
rs= np.arange(0,20)

In [36]:
print(rs)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [37]:
rs%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [38]:
rs[rs%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
rs[rs%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Slicing array

In [40]:
l3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
l3[1:,:2]

array([[4, 5],
       [7, 8]])

In [42]:
l3[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
l3[:,2]

array([3, 6, 9])

In [44]:
l3.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Array operation

In [45]:
x1= np.array